### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by DrJZhou** [koreyou/text-gcn-chainer#1]
I am sorry to disturb you. For the net.py, the input of the GCN is x=I (identity matrix), the shape of the x is (adj.shape[1], adj.shape[1]), but the feat_size is 200 rather than adj.shape[1] and you don't use  input_repr here. Do I misunderstand it? Thanks.

**Comment by koreyou** [comment]
Hello. Thanks for the interest to my code.

You are correct.
I am not using `input_repr` (I deleted `input_repr` in d380365e950fc3e8c8b08d0fb413a1a575ec2c00) as you pointed out. The input is transformed to 200d (=`feat_size`) vector in the first `GraphConvolution` layer.

I intentionally made this somewhat inefficient implementation to be consistent with the paper; i.e. apply dropout to identity matrix.

Please close the issue if you are OK with the above explanation.
